Improve log message serialisation fallback. Log the failure
justeat/JustLog pull request #93
Opened 2021-02-02 10:55 UTC by e-oneg1n

- Added JSON validation to provide additional information about non-serialisable objects inside `userInfo` of NSError objects
- Added warning logs where  JSON serialisation might failed

2021-02-02 11:25 UTC, ssh88 approved these changes

2021-02-02 11:31 UTC, antoniostrijdom commented on JustLog/Extensions/NSError+Readability.swift
> +                    flattenedUserInfo[key] = nonSerialisableObject
This was so much easier in the Obj-C days 😀 `[value description]` done.

2021-02-02 11:31 UTC, antoniostrijdom commented on JustLog/Classes/Logger.swift
> +                        self.warning("Object { \($0) } is filted out from the log", userInfo: ["Module": "JustLog"])
Small typo "filtered".

2021-02-02 11:32 UTC, antoniostrijdom requested changes
Small typo. Also, are there already tests for handling these non-serialisable error cases?

2021-02-02 13:16 UTC, e-oneg1n commented
> Small typo. Also, are there already tests for handling these non-serialisable error cases?

No. There are no tests for these cases for now. I'm planning to analyse the 'problems' logs later and return back with tests. I need to see a whole picture of the problem.

2021-02-02 13:35 UTC, e-oneg1n commented
Unit tests will be added to the PR with next commit

2021-02-02 14:53 UTC, antoniostrijdom approved these changes

2021-02-03 10:34 UTC, albertodebortoli approved these changes

2021-02-03 10:36 UTC, merged